# SecurityProperties类属性自定义配置
security-properties:
  code:
    image:
      width: 67
      height: 32
      length: 6
      expireIn: 120
      # url:
    sms:
      length: 6
      expireIn: 120
      # url:
    social:
      filterProcessesUrl:
      qq:
        appId:
        appSecret:
        providerId: qq
      weChat:
         appId:
         appSecret:
         providerId: qq
  oauth2:
      clients[0]:
        clientId: imooc
        clientSecret: imoocsecret
        accessTokenValiditySeconds: 72000
        redirectUris: http://www.baidu.com
      clients[1]:
        clientId: bfd
        clientSecret: bfdsecret
        redirectUris: http://www.baidu.com
#      storeType: redis



spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/kaleidoscope_mall?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    ######################### Druid连接池的配置信息  #################
    initialSize: 5                                 #初始化连接大小
    minIdle: 5                                     #最小连接池数量
    maxActive: 20                                  #最大连接池数量
    maxWait: 60000                                 #获取连接时最大等待时间，单位毫秒
    timeBetweenEvictionRunsMillis: 60000           #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 300000             #配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 1 FROM DUAL            #测试连接
    testWhileIdle: true                            #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
    testOnBorrow: false                            #获取连接时执行检测，建议关闭，影响性能
    testOnReturn: false                            #归还连接时执行检测，建议关闭，影响性能
    poolPreparedStatements: false                  #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
    maxPoolPreparedStatementPerConnectionSize: 20  #开启poolPreparedStatements后生效
    filters: stat,wall                             #  配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
    connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000'  #通过connectProperties属性来打开mergeSql功能;慢SQL记录

  redis:
    host: 127.0.0.1
    port: 6379